name: exprgen
version: 0.1.0.0
author: Alexander Altergot <avaltergot@gmail.com>
maintainer: Alexander Altergot <avaltergot@gmail.com>
license: MIT
license-file: LICENSE
github: aaltergot/exprgen

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - exprgen

executables:
  exprgen:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
      - exprgen

library:
  source-dirs:
    - src

dependencies:
  - base == 4.*
  - MonadRandom
  - monad-control
  - mtl
  - optparse-applicative
  - random
  - safe-exceptions
  - text
  - template-haskell
