name: exprgen
version: 0.1.0
maintainer: Alexander Altergot <avaltergot@gmail.com>
license: OtherLicense 
github: aaltergot/exprgen

executables:
  exprgen:
    main: Main.hs
    source-dirs:
      - src

library:
  source-dirs:
    - src

dependencies:
  - base == 4.*
